### ISSUE TITLE
boxy fails to compile 

### ISSUE THREAD

**Issue by Outstep** [Bareflank/boxy#51]
Hello,

While testing out the Bareflank capabilities for possible use in a project, I wanted to compile up Boxy on my Debian 9 (x86_64) system and while it seems that most things were  compiling, I just ran into some errors:
 
==================================
Scanning dependencies of target boxy_domain
[  4%] Building CXX object src/domain/CMakeFiles/boxy_domain.dir/domain.cpp.o
[  8%] Linking CXX static library libboxy_domain.a
Scanning dependencies of target boxy_hve
[ 17%] Building CXX object src/hve/CMakeFiles/boxy_hve.dir/arch/intel_x64/virt/vclock.cpp.o
[ 17%] Building CXX object src/hve/CMakeFiles/boxy_hve.dir/arch/intel_x64/emulation/cpuid.cpp.o
[ 26%] Building CXX object src/hve/CMakeFiles/boxy_hve.dir/arch/intel_x64/emulation/x2apic.cpp.o
[ 26%] Building CXX object src/hve/CMakeFiles/boxy_hve.dir/arch/intel_x64/emulation/mtrr.cpp.o
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:319:23: error: 'tsc' is not a class, namespace, or enumeration
    auto tsc = ::x64::tsc::get();
                      ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:319:10: note: 'tsc' declared here
    auto tsc = ::x64::tsc::get();
         ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:340:23: error: 'tsc' is not a class, namespace, or enumeration
    auto tsc = ::x64::tsc::get();
                      ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:340:10: note: 'tsc' declared here
    auto tsc = ::x64::tsc::get();
         ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:374:27: error: 'tsc' is not a class, namespace, or enumeration
    if (auto tsc = ::x64::tsc::get(); tsc < next_event) {
                          ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:374:14: note: 'tsc' declared here
    if (auto tsc = ::x64::tsc::get(); tsc < next_event) {
             ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:408:35: error: no member named 'tsc' in namespace 'x64'
        m_next_event_tsc = ::x64::tsc::get() + vcpu->rbx();
                           ~~~~~~~^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:572:27: error: 'tsc' is not a class, namespace, or enumeration
    if (auto tsc = ::x64::tsc::get(); tsc < m_next_event_tsc) {
                          ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:572:14: note: 'tsc' declared here
    if (auto tsc = ::x64::tsc::get(); tsc < m_next_event_tsc) {
             ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp:610:9: error: no matching constructor for initialization of
      'const vcpu_delegate_t &' (aka 'const delegate<void (bfobject *)> &')
        {&vclock_handler::resume_delegate, this}
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:303:5: note: candidate template ignored: could not match 'bfobject *' against
      'bfvmm::intel_x64::vcpu *'
    delegate(Ret(C::*memfn)(Args...), C *obj)
    ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:343:5: note: candidate template ignored: could not match
      'void (bfobject *) const' against 'void (bfvmm::intel_x64::vcpu *)'
    delegate(Ret(C::*memfn)(Args...) const, C *obj)
    ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:380:14: note: candidate template ignored: could not match
      'void (bfobject *) const' against 'void (bfvmm::intel_x64::vcpu *)'
             delegate(Ret(C::*memfn)(Args...) const, const C *obj)
             ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:268:5: note: candidate constructor template not viable: requires single
      argument 'fn', but 2 arguments were provided
    delegate(F fn)
    ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:234:5: note: candidate constructor not viable: requires single argument 'fn',
      but 2 arguments were provided
    delegate(Ret(*fn)(Args...))
    ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:396:5: note: candidate constructor not viable: requires single argument
      'other', but 2 arguments were provided
    delegate(const delegate &other) :
    ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:405:5: note: candidate constructor not viable: requires single argument
      'other', but 2 arguments were provided
    delegate(delegate &&other) :
    ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfdelegate.h:209:5: note: candidate constructor not viable: requires 0 arguments, but 2
      were provided
    delegate() : m_call{nullptr}, m_vtbl{nullptr}
    ^
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfvmm/hve/arch/intel_x64/vcpu.h:143:61: note: passing argument to parameter 'd' here
    VIRTUAL void add_resume_delegate(const vcpu_delegate_t &d) noexcept
                                                            ^
/home/lonnie/Cloud/Type-2/boxy/bfvmm/src/hve/arch/intel_x64/emulation/x2apic.cpp:45:17: error: no member named 'is_host_vcpu' in namespace 'vcpuid'; did you
      mean 'is_host_vm_vcpu'?
    if (vcpuid::is_host_vcpu(vcpu->id())) {
        ~~~~~~~~^~~~~~~~~~~~
                is_host_vm_vcpu
/home/lonnie/Cloud/Type-2/boxy/build/prefixes/x86_64-vmm-elf/include/bfvcpuid.h:60:27: note: 'is_host_vm_vcpu' declared here
    constexpr inline bool is_host_vm_vcpu(type id)
                          ^
6 errors generated.
make[5]: *** [src/hve/CMakeFiles/boxy_hve.dir/build.make:102: src/hve/CMakeFiles/boxy_hve.dir/arch/intel_x64/virt/vclock.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
1 error generated.
make[5]: *** [src/hve/CMakeFiles/boxy_hve.dir/build.make:89: src/hve/CMakeFiles/boxy_hve.dir/arch/intel_x64/emulation/x2apic.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:182: src/hve/CMakeFiles/boxy_hve.dir/all] Error 2
make[3]: *** [Makefile:118: all] Error 2
make[2]: *** [CMakeFiles/boxy_bfvmm_x86_64-vmm-elf.dir/build.make:113: boxy_bfvmm/x86_64-vmm-elf/stamp/boxy_bfvmm_x86_64-vmm-elf-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:3046: CMakeFiles/boxy_bfvmm_x86_64-vmm-elf.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
lonnie@debian:~/Cloud/Type-2/boxy/build$ 

==================================

Any ideas on this?

**Comment by chp-io** [comment]
Hello, a previous commit came with changes to the hypervisor and the hypervisor submodule couldn't be updated at the same time since the hypervisor repository needed the PR to be merged first.
Fix is here: [update hypervisor submodule](https://github.com/Bareflank/boxy/pull/52)

**Comment by rianquinn** [comment]
I think this has been addressed with the latest pushes.
